# Generated by Django 4.2.4 on 2024-07-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='transaction_status',
            field=models.CharField(choices=[('SUCCESS', 'success'), ('FAILED', 'failed')], default='FAILED', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'deposit'), ('WITHDRAWAL', 'withdrawal')], max_length=10),
        ),
    ]
