# Generated by Django 4.2.4 on 2024-06-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bank_name',
            field=models.CharField(default='State Bank of Myworld', max_length=200),
            preserve_default=False,
        ),
    ]
