# Generated by Django 4.2.4 on 2024-06-20 17:55

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='m_pin',
            field=models.CharField(default=1234, max_length=4, validators=[account.models.validate_length_4]),
            preserve_default=False,
        ),
    ]
